### ISSUE TITLE
packing_api not working as intended.

### ISSUE THREAD

**Issue by cozek** [dream-lab/prometheus-kube#3]
1. uvicorn server not working as intended.
```
(iisc) [azureuser@iisc-proj-vm packing_api]$ uvicorn packing:app --host localhost
/home/azureuser/prometheus-kube/packing_api/rl_train/gym-packing/gym_packing/envs/packing_env.py:77: RuntimeWarning: divide by zero encountered in divide
  data = data / self.max_vals
/home/azureuser/prometheus-kube/packing_api/rl_train/gym-packing/gym_packing/envs/packing_env.py:77: RuntimeWarning: overflow encountered in divide
  data = data / self.max_vals
/home/azureuser/prometheus-kube/packing_api/rl_train/gym-packing/gym_packing/envs/packing_env.py:77: RuntimeWarning: invalid value encountered in divide
  data = data / self.max_vals
/home/azureuser/prometheus-kube/packing_api/rl_train/gym-packing/gym_packing/envs/packing_env.py:99: RuntimeWarning: overflow encountered in cast
  self.state = np.vstack(
Traceback (most recent call last):
  File "/home/azureuser/.conda/envs/iisc/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/azureuser/.conda/envs/iisc/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/azureuser/.conda/envs/iisc/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/azureuser/.conda/envs/iisc/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/azureuser/.conda/envs/iisc/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/azureuser/.conda/envs/iisc/lib/python3.8/site-packages/uvicorn/main.py", line 404, in main
    run(
  File "/home/azureuser/.conda/envs/iisc/lib/python3.8/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/home/azureuser/.conda/envs/iisc/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/azureuser/.conda/envs/iisc/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/azureuser/.conda/envs/iisc/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/azureuser/.conda/envs/iisc/lib/python3.8/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/azureuser/.conda/envs/iisc/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/azureuser/.conda/envs/iisc/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/azureuser/prometheus-kube/packing_api/./packing.py", line 5, in <module>
    from rl import rl_pack
  File "/home/azureuser/prometheus-kube/packing_api/./rl.py", line 31, in <module>
    model = MaskablePPO.load(path, env=env)
  File "/home/azureuser/.conda/envs/iisc/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 782, in load
    check_for_correct_spaces(env, data["observation_space"], data["action_space"])
  File "/home/azureuser/.conda/envs/iisc/lib/python3.8/site-packages/stable_baselines3/common/utils.py", line 226, in check_for_correct_spaces
    raise ValueError(f"Observation spaces do not match: {observation_space} != {env.observation_space}")
ValueError: Observation spaces do not match: Box([[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], (4, 5), float32) != Box([[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], (16, 5), float32)
```
3. Path to model is incorrect in `rl.py` in packing API ?
`PATH = "rl_train/models/best_model"`

**Comment by S1LV3RJ1NX** [comment]
Solved.
